### ISSUE TITLE
请修复read.me

### ISSUE THREAD

**Issue by nemon-** [PaddlePaddle/RLSchool#16]
python 2.7.6 ,pip安装最新版RLSchool后，用read.me代码不能运行，改为以下代码通过：
from rlschool import env as make_env
env = make_env.LiftSim()
observation = env.reset()
action = [2, 0, 4, 0, 7, 0, 10, 0]
for i in range(100):
    env.render()    # use render to show animation
    next_obs, reward, done, info = env.step(action)

**Comment by nemon-** [comment]
是这个文件：
https://github.com/PaddlePaddle/RLSchool/blob/master/rlschool/liftsim/README.md

**Comment by TomorrowIsAnOtherDay** [comment]
READE 中创建环境调用的接口是：
`env = make_env('LiftSim')`
而你提供的代码是：
`env = make_env.LiftSim()`
请更正你的代码再测试一下。

**Comment by xueeinstein** [comment]
@nemon- 这个是新添加环境后加进去的，还没有在pip源上更新，使用[这个页面上的](https://github.com/PaddlePaddle/RLSchool/tree/master/rlschool/quadrotor)安装方式就需要这个新的make_env接口。旧的LiftSim readme在[这里](https://github.com/PaddlePaddle/RLSchool/blob/1f81b57395b463bb2174e686e6fd566f14253209/rlschool/liftsim/README.md)。
