### ISSUE TITLE
代码存在困惑点

### ISSUE THREAD

**Issue by simsimiSION** [PaddlePaddle/RLSchool#32]
在quadrotorsim.py中256-258行
```
        self.coordination_converter_to_world = self.rotation_matrix
        self.coordination_converter_to_body = np.linalg.inv(
        self.rotation_matrix)
```
这个不是应该用 self._coordination_converter_to_world 和 self._coordination_converter_to_body 这两个吗，还是我理解的有问题呀，谢谢您的回答

**Comment by xueeinstein** [comment]
@simsimiSION 多谢提醒，这个typos已在v0.3.2修复。
