### ISSUE TITLE
The image in /rlschool/liftsim/README.md#Action 

### ISSUE THREAD

**Issue by cslayers** [PaddlePaddle/RLSchool#5]
![image](https://user-images.githubusercontent.com/17827646/62700991-c8f3a100-ba15-11e9-8e3d-27c662f85b81.png)

contains 2 "电梯3".
the left one is actually "电梯2"？

**Comment by WorldEditors** [comment]
Yes, there's a mistake in the sketch. It should be "电梯2"
We will fix this problem shortly, thanks for point out.
