### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chencjiajy** [PaddlePaddle/RLSchool#7]
hi, maybe the `setup.py` is not robust enouph(or maybe it's just a tool can only be installed in Linux), I failed to install it until I made some changes.

**environment**:
platform: windows 10
python: python 3.6.1
error:
 F:code\RLSchool-master>pip install .
Processing f:code\rlschool-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JL\AppData\Local\Temp\pip-4flifg6e-build\setup.py", line 20, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 22: illegal multibyte sequence

**my sollution**:
change setup.py, line 19 to : `with open('README.md', 'r',encoding='utf-8') as fh:`

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for pointing out!
This issue results from the Chinese documentation in README.md, and we have solved this issue in #9.
